spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rename
    username: postgres
    password: postgres

application:
  security:
    jwt:
      secret-key: 566B58703273357638792F423F4528482B4D6251655468576D5A713374367739
      expiration: 86400000
      refresh-token:
        expiration: 604800000

